### ISSUE TITLE
GitHub Webhooks Setup

### ISSUE THREAD

**Issue by sballan** [sballan/grille#1]
Find all the webhooks that will be needed and set them all up

**Comment by thinkocapo** [comment]
comment

**Comment by thinkocapo** [comment]
comment2

**Comment by thinkocapo** [comment]
comment3

**Comment by thinkocapo** [comment]
need to understand (at some point) if we need all these. Big Question - save URLs in the fields of our model (hotlinking) or save the data itself?

**Comment by thinkocapo** [comment]
Question-payLoadParser is returning a slimmed down version of the body that Github sent us in their original POST request?

**Comment by sballan** [comment]
Yes, payload parser returns a slimmed down but also organized version of the original post request

**Comment by sballan** [comment]
For now I think it's a good idea to do hotlinking AND save the actual data, until we've had a chance to build more of the site.  I expect we'll end up using the actual data, but for now I think it's a good idea to save the urls too just in case.
