### ISSUE TITLE
Fix Privacy Error when using grille.io

### ISSUE THREAD

**Issue by sballan** [sballan/grille#171]
<img width="1075" alt="screenshot_56" src="https://cloud.githubusercontent.com/assets/4956929/13098631/9e809f0a-d4f8-11e5-8de7-8f76f0405f03.png">

**Comment by sballan** [comment]
Do we have to buy an SSL certificate?

This article may be helpful: https://lostechies.com/derickbailey/2014/02/12/heroku-and-ssl-fixing-this-sites-security-certificate-is-not-trusted-on-android-and-other-devices/

**Comment by ssarda77** [comment]
Namecheap SSL cert starts at $9/month. Let's hold off for a little while.

**Comment by sballan** [comment]
Wow that is crazy
