### ISSUE TITLE
Fix the order of the columns

### ISSUE THREAD

**Issue by sballan** [sballan/grille#186]
Related to #176

**Comment by sballan** [comment]
@ssarda77  I think we may need to make a Labels schema, and that schema can also function as the Lane. I don't see any way around it. What do you think?

**Comment by ssarda77** [comment]
@sballan How about lane order? How do we keep track of this without a Lane schema?

**Comment by sballan** [comment]
@ssarda77 I have two ideas about that, one kinda lame, one kinda insane but kinda cool.

We could have a position field on our label schema, and labels that are used as columns ( designated by a particular color we use for columns, probably grey) would put a number in that field.

The other idea would be to have a range of acceptable colors for a column label, eg #222222 to #222252.  They would all look approximately grey, but we could use the value of the color field to keep track of the position.  This might take some clever presave hooks and stuff to make sure we're always in a valid range and things like that, but I think this idea is cool!

**Comment by ssarda** [comment]
Please remove ssarda@umd.edu from your github project. I am Shrutii Sarda,
a graduate student @ University of Maryland.

**Comment by ssarda77** [comment]
@sballan I like the first idea better. We could just use the position field to signify whether it's a column or not (like zero means no column or something). I think the second one is too hacky.

**Comment by sballan** [comment]
Great. I still like the idea of having a dedicated column color though, even if it just helps you visually while looking on github.

**Comment by ssarda77** [comment]
@sballan Does this issue relate to issue #178? Is that the same Labels Schema?

**Comment by sballan** [comment]
@ssarda77 loks to me like #178 is outdated, since we decided to keep the Labels Schema.  I'll archive it.

**Comment by sballan** [comment]
Columns being completely rewritten.
