### ISSUE TITLE
ShowGrillData- Ctrl/Fac/Routes (tag,label,priority)

### ISSUE THREAD

**Issue by thinkocapo** [sballan/grille#36]
This means stuff that users are putting onto the cards, but its not persisted to GithubAPI. Its just stored on our end.

**Comment by thinkocapo** [comment]
from /userSettings landing page, can click on a repo and it sends its githubID to the homestate. Can use getOneRepo function to use this githubID to fetch the repo details, and populate the card

**Comment by sballan** [comment]
SO if we add another comment, we should be able to see it in our server
